//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.EmpleadoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleado", Namespace="http://schemas.datacontract.org/2004/07/BAL")]
    [System.SerializableAttribute()]
    public partial class Empleado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AreaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarrioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CargoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CelularCorporativoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CelularPersonalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoPersonalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepartamentoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoSedeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepartamentoSedeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionResidenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpleadoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoCivilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaActivacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FotoEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GrupoSanguineoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MunicipioIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MunicipioSedeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MunicipioSedeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreSedeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaisIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisSedeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaisSedeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimerNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SedeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoFijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoDocumentoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalRegistrosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuarioIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AreaID {
            get {
                return this.AreaIDField;
            }
            set {
                if ((this.AreaIDField.Equals(value) != true)) {
                    this.AreaIDField = value;
                    this.RaisePropertyChanged("AreaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Barrio {
            get {
                return this.BarrioField;
            }
            set {
                if ((object.ReferenceEquals(this.BarrioField, value) != true)) {
                    this.BarrioField = value;
                    this.RaisePropertyChanged("Barrio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CargoID {
            get {
                return this.CargoIDField;
            }
            set {
                if ((this.CargoIDField.Equals(value) != true)) {
                    this.CargoIDField = value;
                    this.RaisePropertyChanged("CargoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CelularCorporativo {
            get {
                return this.CelularCorporativoField;
            }
            set {
                if ((object.ReferenceEquals(this.CelularCorporativoField, value) != true)) {
                    this.CelularCorporativoField = value;
                    this.RaisePropertyChanged("CelularCorporativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CelularPersonal {
            get {
                return this.CelularPersonalField;
            }
            set {
                if ((object.ReferenceEquals(this.CelularPersonalField, value) != true)) {
                    this.CelularPersonalField = value;
                    this.RaisePropertyChanged("CelularPersonal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronicoPersonal {
            get {
                return this.CorreoElectronicoPersonalField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoPersonalField, value) != true)) {
                    this.CorreoElectronicoPersonalField = value;
                    this.RaisePropertyChanged("CorreoElectronicoPersonal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartamentoID {
            get {
                return this.DepartamentoIDField;
            }
            set {
                if ((this.DepartamentoIDField.Equals(value) != true)) {
                    this.DepartamentoIDField = value;
                    this.RaisePropertyChanged("DepartamentoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartamentoSede {
            get {
                return this.DepartamentoSedeField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoSedeField, value) != true)) {
                    this.DepartamentoSedeField = value;
                    this.RaisePropertyChanged("DepartamentoSede");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartamentoSedeID {
            get {
                return this.DepartamentoSedeIDField;
            }
            set {
                if ((this.DepartamentoSedeIDField.Equals(value) != true)) {
                    this.DepartamentoSedeIDField = value;
                    this.RaisePropertyChanged("DepartamentoSedeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionResidencia {
            get {
                return this.DireccionResidenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionResidenciaField, value) != true)) {
                    this.DireccionResidenciaField = value;
                    this.RaisePropertyChanged("DireccionResidencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpleadoID {
            get {
                return this.EmpleadoIDField;
            }
            set {
                if ((this.EmpleadoIDField.Equals(value) != true)) {
                    this.EmpleadoIDField = value;
                    this.RaisePropertyChanged("EmpleadoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoCivil {
            get {
                return this.EstadoCivilField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoCivilField, value) != true)) {
                    this.EstadoCivilField = value;
                    this.RaisePropertyChanged("EstadoCivil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaActivacion {
            get {
                return this.FechaActivacionField;
            }
            set {
                if ((this.FechaActivacionField.Equals(value) != true)) {
                    this.FechaActivacionField = value;
                    this.RaisePropertyChanged("FechaActivacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FotoEmpleado {
            get {
                return this.FotoEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoEmpleadoField, value) != true)) {
                    this.FotoEmpleadoField = value;
                    this.RaisePropertyChanged("FotoEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GrupoSanguineo {
            get {
                return this.GrupoSanguineoField;
            }
            set {
                if ((object.ReferenceEquals(this.GrupoSanguineoField, value) != true)) {
                    this.GrupoSanguineoField = value;
                    this.RaisePropertyChanged("GrupoSanguineo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MunicipioID {
            get {
                return this.MunicipioIDField;
            }
            set {
                if ((this.MunicipioIDField.Equals(value) != true)) {
                    this.MunicipioIDField = value;
                    this.RaisePropertyChanged("MunicipioID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MunicipioSede {
            get {
                return this.MunicipioSedeField;
            }
            set {
                if ((object.ReferenceEquals(this.MunicipioSedeField, value) != true)) {
                    this.MunicipioSedeField = value;
                    this.RaisePropertyChanged("MunicipioSede");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MunicipioSedeID {
            get {
                return this.MunicipioSedeIDField;
            }
            set {
                if ((this.MunicipioSedeIDField.Equals(value) != true)) {
                    this.MunicipioSedeIDField = value;
                    this.RaisePropertyChanged("MunicipioSedeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreArea {
            get {
                return this.NombreAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreAreaField, value) != true)) {
                    this.NombreAreaField = value;
                    this.RaisePropertyChanged("NombreArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCargo {
            get {
                return this.NombreCargoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCargoField, value) != true)) {
                    this.NombreCargoField = value;
                    this.RaisePropertyChanged("NombreCargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreSede {
            get {
                return this.NombreSedeField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreSedeField, value) != true)) {
                    this.NombreSedeField = value;
                    this.RaisePropertyChanged("NombreSede");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroEmpleado {
            get {
                return this.NumeroEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroEmpleadoField, value) != true)) {
                    this.NumeroEmpleadoField = value;
                    this.RaisePropertyChanged("NumeroEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaisID {
            get {
                return this.PaisIDField;
            }
            set {
                if ((this.PaisIDField.Equals(value) != true)) {
                    this.PaisIDField = value;
                    this.RaisePropertyChanged("PaisID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaisSede {
            get {
                return this.PaisSedeField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisSedeField, value) != true)) {
                    this.PaisSedeField = value;
                    this.RaisePropertyChanged("PaisSede");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaisSedeID {
            get {
                return this.PaisSedeIDField;
            }
            set {
                if ((this.PaisSedeIDField.Equals(value) != true)) {
                    this.PaisSedeIDField = value;
                    this.RaisePropertyChanged("PaisSedeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerApellido {
            get {
                return this.PrimerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerApellidoField, value) != true)) {
                    this.PrimerApellidoField = value;
                    this.RaisePropertyChanged("PrimerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerNombre {
            get {
                return this.PrimerNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerNombreField, value) != true)) {
                    this.PrimerNombreField = value;
                    this.RaisePropertyChanged("PrimerNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SedeID {
            get {
                return this.SedeIDField;
            }
            set {
                if ((this.SedeIDField.Equals(value) != true)) {
                    this.SedeIDField = value;
                    this.RaisePropertyChanged("SedeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoApellido {
            get {
                return this.SegundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoApellidoField, value) != true)) {
                    this.SegundoApellidoField = value;
                    this.RaisePropertyChanged("SegundoApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoNombre {
            get {
                return this.SegundoNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoNombreField, value) != true)) {
                    this.SegundoNombreField = value;
                    this.RaisePropertyChanged("SegundoNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonoFijo {
            get {
                return this.TelefonoFijoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoFijoField, value) != true)) {
                    this.TelefonoFijoField = value;
                    this.RaisePropertyChanged("TelefonoFijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoDocumentoID {
            get {
                return this.TipoDocumentoIDField;
            }
            set {
                if ((this.TipoDocumentoIDField.Equals(value) != true)) {
                    this.TipoDocumentoIDField = value;
                    this.RaisePropertyChanged("TipoDocumentoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRegistros {
            get {
                return this.TotalRegistrosField;
            }
            set {
                if ((this.TotalRegistrosField.Equals(value) != true)) {
                    this.TotalRegistrosField = value;
                    this.RaisePropertyChanged("TotalRegistros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuarioID {
            get {
                return this.UsuarioIDField;
            }
            set {
                if ((this.UsuarioIDField.Equals(value) != true)) {
                    this.UsuarioIDField = value;
                    this.RaisePropertyChanged("UsuarioID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InformacionFamiliar", Namespace="http://schemas.datacontract.org/2004/07/BAL")]
    [System.SerializableAttribute()]
    public partial class InformacionFamiliar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EdadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpleadoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InformacionFamiliarIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreParentescoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OcupacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentescoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuarioIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Edad {
            get {
                return this.EdadField;
            }
            set {
                if ((this.EdadField.Equals(value) != true)) {
                    this.EdadField = value;
                    this.RaisePropertyChanged("Edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpleadoID {
            get {
                return this.EmpleadoIDField;
            }
            set {
                if ((this.EmpleadoIDField.Equals(value) != true)) {
                    this.EmpleadoIDField = value;
                    this.RaisePropertyChanged("EmpleadoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InformacionFamiliarID {
            get {
                return this.InformacionFamiliarIDField;
            }
            set {
                if ((this.InformacionFamiliarIDField.Equals(value) != true)) {
                    this.InformacionFamiliarIDField = value;
                    this.RaisePropertyChanged("InformacionFamiliarID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreParentesco {
            get {
                return this.NombreParentescoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreParentescoField, value) != true)) {
                    this.NombreParentescoField = value;
                    this.RaisePropertyChanged("NombreParentesco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ocupacion {
            get {
                return this.OcupacionField;
            }
            set {
                if ((object.ReferenceEquals(this.OcupacionField, value) != true)) {
                    this.OcupacionField = value;
                    this.RaisePropertyChanged("Ocupacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentescoID {
            get {
                return this.ParentescoIDField;
            }
            set {
                if ((this.ParentescoIDField.Equals(value) != true)) {
                    this.ParentescoIDField = value;
                    this.RaisePropertyChanged("ParentescoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuarioID {
            get {
                return this.UsuarioIDField;
            }
            set {
                if ((this.UsuarioIDField.Equals(value) != true)) {
                    this.UsuarioIDField = value;
                    this.RaisePropertyChanged("UsuarioID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExperienciaLaboral", Namespace="http://schemas.datacontract.org/2004/07/BAL")]
    [System.SerializableAttribute()]
    public partial class ExperienciaLaboral : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpleadoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExperienciaLaboralIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaIngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRetiroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FuncionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MunicipioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreAreaTrabajoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreSectorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuarioIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cargo {
            get {
                return this.CargoField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoField, value) != true)) {
                    this.CargoField = value;
                    this.RaisePropertyChanged("Cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpleadoID {
            get {
                return this.EmpleadoIDField;
            }
            set {
                if ((this.EmpleadoIDField.Equals(value) != true)) {
                    this.EmpleadoIDField = value;
                    this.RaisePropertyChanged("EmpleadoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Empresa {
            get {
                return this.EmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresaField, value) != true)) {
                    this.EmpresaField = value;
                    this.RaisePropertyChanged("Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExperienciaLaboralID {
            get {
                return this.ExperienciaLaboralIDField;
            }
            set {
                if ((this.ExperienciaLaboralIDField.Equals(value) != true)) {
                    this.ExperienciaLaboralIDField = value;
                    this.RaisePropertyChanged("ExperienciaLaboralID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaIngreso {
            get {
                return this.FechaIngresoField;
            }
            set {
                if ((this.FechaIngresoField.Equals(value) != true)) {
                    this.FechaIngresoField = value;
                    this.RaisePropertyChanged("FechaIngreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRetiro {
            get {
                return this.FechaRetiroField;
            }
            set {
                if ((this.FechaRetiroField.Equals(value) != true)) {
                    this.FechaRetiroField = value;
                    this.RaisePropertyChanged("FechaRetiro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Funciones {
            get {
                return this.FuncionesField;
            }
            set {
                if ((object.ReferenceEquals(this.FuncionesField, value) != true)) {
                    this.FuncionesField = value;
                    this.RaisePropertyChanged("Funciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Municipio {
            get {
                return this.MunicipioField;
            }
            set {
                if ((object.ReferenceEquals(this.MunicipioField, value) != true)) {
                    this.MunicipioField = value;
                    this.RaisePropertyChanged("Municipio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreAreaTrabajo {
            get {
                return this.NombreAreaTrabajoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreAreaTrabajoField, value) != true)) {
                    this.NombreAreaTrabajoField = value;
                    this.RaisePropertyChanged("NombreAreaTrabajo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreSector {
            get {
                return this.NombreSectorField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreSectorField, value) != true)) {
                    this.NombreSectorField = value;
                    this.RaisePropertyChanged("NombreSector");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuarioID {
            get {
                return this.UsuarioIDField;
            }
            set {
                if ((this.UsuarioIDField.Equals(value) != true)) {
                    this.UsuarioIDField = value;
                    this.RaisePropertyChanged("UsuarioID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormacionAcademica", Namespace="http://schemas.datacontract.org/2004/07/BAL")]
    [System.SerializableAttribute()]
    public partial class FormacionAcademica : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpleadoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaFinalizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FormacionAcademicaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstitucionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MunicipioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NivelFormacionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreNivelFormacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloObtenidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuarioIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpleadoID {
            get {
                return this.EmpleadoIDField;
            }
            set {
                if ((this.EmpleadoIDField.Equals(value) != true)) {
                    this.EmpleadoIDField = value;
                    this.RaisePropertyChanged("EmpleadoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaFinalizacion {
            get {
                return this.FechaFinalizacionField;
            }
            set {
                if ((this.FechaFinalizacionField.Equals(value) != true)) {
                    this.FechaFinalizacionField = value;
                    this.RaisePropertyChanged("FechaFinalizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((this.FechaInicioField.Equals(value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FormacionAcademicaID {
            get {
                return this.FormacionAcademicaIDField;
            }
            set {
                if ((this.FormacionAcademicaIDField.Equals(value) != true)) {
                    this.FormacionAcademicaIDField = value;
                    this.RaisePropertyChanged("FormacionAcademicaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Institucion {
            get {
                return this.InstitucionField;
            }
            set {
                if ((object.ReferenceEquals(this.InstitucionField, value) != true)) {
                    this.InstitucionField = value;
                    this.RaisePropertyChanged("Institucion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Municipio {
            get {
                return this.MunicipioField;
            }
            set {
                if ((object.ReferenceEquals(this.MunicipioField, value) != true)) {
                    this.MunicipioField = value;
                    this.RaisePropertyChanged("Municipio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NivelFormacionID {
            get {
                return this.NivelFormacionIDField;
            }
            set {
                if ((this.NivelFormacionIDField.Equals(value) != true)) {
                    this.NivelFormacionIDField = value;
                    this.RaisePropertyChanged("NivelFormacionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreNivelFormacion {
            get {
                return this.NombreNivelFormacionField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreNivelFormacionField, value) != true)) {
                    this.NombreNivelFormacionField = value;
                    this.RaisePropertyChanged("NombreNivelFormacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TituloObtenido {
            get {
                return this.TituloObtenidoField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloObtenidoField, value) != true)) {
                    this.TituloObtenidoField = value;
                    this.RaisePropertyChanged("TituloObtenido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuarioID {
            get {
                return this.UsuarioIDField;
            }
            set {
                if ((this.UsuarioIDField.Equals(value) != true)) {
                    this.UsuarioIDField = value;
                    this.RaisePropertyChanged("UsuarioID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmpleadoService.IEmpleadoService")]
    public interface IEmpleadoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoService/ObtenerEmpleadoByUsuarioID", ReplyAction="http://tempuri.org/IEmpleadoService/ObtenerEmpleadoByUsuarioIDResponse")]
        System.Collections.Generic.List<WEB.EmpleadoService.Empleado> ObtenerEmpleadoByUsuarioID(int UsuarioID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoService/ActualizarInformacionUsuario", ReplyAction="http://tempuri.org/IEmpleadoService/ActualizarInformacionUsuarioResponse")]
        int ActualizarInformacionUsuario(
                    int UsuarioID, 
                    string PrimerNombre, 
                    string SegundoNombre, 
                    string PrimerApellido, 
                    string SegundoApellido, 
                    int TipoDocumentoID, 
                    string Documento, 
                    int CargoID, 
                    System.DateTime FechaNacimiento, 
                    string DireccionResidencia, 
                    string Barrio, 
                    string TelefonoFijo, 
                    string CelularPersonal, 
                    string CelularCorporativo, 
                    string CorreoPersonal, 
                    string CorreoCorporativo, 
                    string GrupoSanguineo, 
                    string EstadoCivil, 
                    int MunicipioID, 
                    int SedeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoService/ObtenerInformacionFamiliarEmpleadoByUsuarioID" +
            "", ReplyAction="http://tempuri.org/IEmpleadoService/ObtenerInformacionFamiliarEmpleadoByUsuarioID" +
            "Response")]
        System.Collections.Generic.List<WEB.EmpleadoService.InformacionFamiliar> ObtenerInformacionFamiliarEmpleadoByUsuarioID(int UsuarioID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoService/ObtenerExperienciaLaboralEmpleadoByUsuarioID", ReplyAction="http://tempuri.org/IEmpleadoService/ObtenerExperienciaLaboralEmpleadoByUsuarioIDR" +
            "esponse")]
        System.Collections.Generic.List<WEB.EmpleadoService.ExperienciaLaboral> ObtenerExperienciaLaboralEmpleadoByUsuarioID(int UsuarioID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoService/GuardarInformacionFamiliar", ReplyAction="http://tempuri.org/IEmpleadoService/GuardarInformacionFamiliarResponse")]
        int GuardarInformacionFamiliar(int EmpleadoID, string Nombres, string Apellidos, string Ocupacion, System.DateTime FechaNacimiento, int ParentescoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoService/ObtenerFormacionAcademicaEmpleadoByUsuarioID", ReplyAction="http://tempuri.org/IEmpleadoService/ObtenerFormacionAcademicaEmpleadoByUsuarioIDR" +
            "esponse")]
        System.Collections.Generic.List<WEB.EmpleadoService.FormacionAcademica> ObtenerFormacionAcademicaEmpleadoByUsuarioID(int UsuarioID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoService/GuardarInformacionAcademica", ReplyAction="http://tempuri.org/IEmpleadoService/GuardarInformacionAcademicaResponse")]
        int GuardarInformacionAcademica(int EmpleadoID, string Institucion, string TituloObtenido, int NivelFormacionID, System.DateTime FechaInicio, System.Nullable<System.DateTime> FechaFinalizacion, int MunicipioID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoService/GuardarExperienciaLaboral", ReplyAction="http://tempuri.org/IEmpleadoService/GuardarExperienciaLaboralResponse")]
        int GuardarExperienciaLaboral(int EmpleadoID, string Empresa, int SectorID, int AreaTrabajoID, string Cargo, System.DateTime FechaIngreso, System.DateTime FechaRetiro, string Funciones, int MunicipioID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoService/ObtenerEmpleados", ReplyAction="http://tempuri.org/IEmpleadoService/ObtenerEmpleadosResponse")]
        System.Collections.Generic.List<WEB.EmpleadoService.Empleado> ObtenerEmpleados(int NoPagina, int NoRegistros, string Login, string NumeroEmpleado, string Cedula, string PrimerApellido, string SegundoApellido, string Nombres, int AreaID, int CargoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoService/EliminarInformacionFamiliarEmpleadoByID", ReplyAction="http://tempuri.org/IEmpleadoService/EliminarInformacionFamiliarEmpleadoByIDRespon" +
            "se")]
        int EliminarInformacionFamiliarEmpleadoByID(int InformacionFamiliarID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoService/EliminarFormacionAcademicaEmpleadoByID", ReplyAction="http://tempuri.org/IEmpleadoService/EliminarFormacionAcademicaEmpleadoByIDRespons" +
            "e")]
        int EliminarFormacionAcademicaEmpleadoByID(int FormacionAcademicaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoService/EliminarExperienciaLaboralEmpleadoByID", ReplyAction="http://tempuri.org/IEmpleadoService/EliminarExperienciaLaboralEmpleadoByIDRespons" +
            "e")]
        int EliminarExperienciaLaboralEmpleadoByID(int ExperienciaLaboralID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmpleadoServiceChannel : WEB.EmpleadoService.IEmpleadoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpleadoServiceClient : System.ServiceModel.ClientBase<WEB.EmpleadoService.IEmpleadoService>, WEB.EmpleadoService.IEmpleadoService {
        
        public EmpleadoServiceClient() {
        }
        
        public EmpleadoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpleadoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<WEB.EmpleadoService.Empleado> ObtenerEmpleadoByUsuarioID(int UsuarioID) {
            return base.Channel.ObtenerEmpleadoByUsuarioID(UsuarioID);
        }
        
        public int ActualizarInformacionUsuario(
                    int UsuarioID, 
                    string PrimerNombre, 
                    string SegundoNombre, 
                    string PrimerApellido, 
                    string SegundoApellido, 
                    int TipoDocumentoID, 
                    string Documento, 
                    int CargoID, 
                    System.DateTime FechaNacimiento, 
                    string DireccionResidencia, 
                    string Barrio, 
                    string TelefonoFijo, 
                    string CelularPersonal, 
                    string CelularCorporativo, 
                    string CorreoPersonal, 
                    string CorreoCorporativo, 
                    string GrupoSanguineo, 
                    string EstadoCivil, 
                    int MunicipioID, 
                    int SedeID) {
            return base.Channel.ActualizarInformacionUsuario(UsuarioID, PrimerNombre, SegundoNombre, PrimerApellido, SegundoApellido, TipoDocumentoID, Documento, CargoID, FechaNacimiento, DireccionResidencia, Barrio, TelefonoFijo, CelularPersonal, CelularCorporativo, CorreoPersonal, CorreoCorporativo, GrupoSanguineo, EstadoCivil, MunicipioID, SedeID);
        }
        
        public System.Collections.Generic.List<WEB.EmpleadoService.InformacionFamiliar> ObtenerInformacionFamiliarEmpleadoByUsuarioID(int UsuarioID) {
            return base.Channel.ObtenerInformacionFamiliarEmpleadoByUsuarioID(UsuarioID);
        }
        
        public System.Collections.Generic.List<WEB.EmpleadoService.ExperienciaLaboral> ObtenerExperienciaLaboralEmpleadoByUsuarioID(int UsuarioID) {
            return base.Channel.ObtenerExperienciaLaboralEmpleadoByUsuarioID(UsuarioID);
        }
        
        public int GuardarInformacionFamiliar(int EmpleadoID, string Nombres, string Apellidos, string Ocupacion, System.DateTime FechaNacimiento, int ParentescoID) {
            return base.Channel.GuardarInformacionFamiliar(EmpleadoID, Nombres, Apellidos, Ocupacion, FechaNacimiento, ParentescoID);
        }
        
        public System.Collections.Generic.List<WEB.EmpleadoService.FormacionAcademica> ObtenerFormacionAcademicaEmpleadoByUsuarioID(int UsuarioID) {
            return base.Channel.ObtenerFormacionAcademicaEmpleadoByUsuarioID(UsuarioID);
        }
        
        public int GuardarInformacionAcademica(int EmpleadoID, string Institucion, string TituloObtenido, int NivelFormacionID, System.DateTime FechaInicio, System.Nullable<System.DateTime> FechaFinalizacion, int MunicipioID) {
            return base.Channel.GuardarInformacionAcademica(EmpleadoID, Institucion, TituloObtenido, NivelFormacionID, FechaInicio, FechaFinalizacion, MunicipioID);
        }
        
        public int GuardarExperienciaLaboral(int EmpleadoID, string Empresa, int SectorID, int AreaTrabajoID, string Cargo, System.DateTime FechaIngreso, System.DateTime FechaRetiro, string Funciones, int MunicipioID) {
            return base.Channel.GuardarExperienciaLaboral(EmpleadoID, Empresa, SectorID, AreaTrabajoID, Cargo, FechaIngreso, FechaRetiro, Funciones, MunicipioID);
        }
        
        public System.Collections.Generic.List<WEB.EmpleadoService.Empleado> ObtenerEmpleados(int NoPagina, int NoRegistros, string Login, string NumeroEmpleado, string Cedula, string PrimerApellido, string SegundoApellido, string Nombres, int AreaID, int CargoID) {
            return base.Channel.ObtenerEmpleados(NoPagina, NoRegistros, Login, NumeroEmpleado, Cedula, PrimerApellido, SegundoApellido, Nombres, AreaID, CargoID);
        }
        
        public int EliminarInformacionFamiliarEmpleadoByID(int InformacionFamiliarID) {
            return base.Channel.EliminarInformacionFamiliarEmpleadoByID(InformacionFamiliarID);
        }
        
        public int EliminarFormacionAcademicaEmpleadoByID(int FormacionAcademicaID) {
            return base.Channel.EliminarFormacionAcademicaEmpleadoByID(FormacionAcademicaID);
        }
        
        public int EliminarExperienciaLaboralEmpleadoByID(int ExperienciaLaboralID) {
            return base.Channel.EliminarExperienciaLaboralEmpleadoByID(ExperienciaLaboralID);
        }
    }
}
