//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.CatalogoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CatalogoService.ISistemaRRHHServices")]
    public interface ISistemaRRHHServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaRRHHServices/CargarCatalogoWCF", ReplyAction="http://tempuri.org/ISistemaRRHHServices/CargarCatalogoWCFResponse")]
        System.Collections.Generic.List<BAL.Catalogo> CargarCatalogoWCF(string listado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaRRHHServices/CargarCatalogoDependienteWCF", ReplyAction="http://tempuri.org/ISistemaRRHHServices/CargarCatalogoDependienteWCFResponse")]
        System.Collections.Generic.List<BAL.Catalogo> CargarCatalogoDependienteWCF(string listado, string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISistemaRRHHServicesChannel : WEB.CatalogoService.ISistemaRRHHServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SistemaRRHHServicesClient : System.ServiceModel.ClientBase<WEB.CatalogoService.ISistemaRRHHServices>, WEB.CatalogoService.ISistemaRRHHServices {
        
        public SistemaRRHHServicesClient() {
        }
        
        public SistemaRRHHServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SistemaRRHHServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SistemaRRHHServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SistemaRRHHServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<BAL.Catalogo> CargarCatalogoWCF(string listado) {
            return base.Channel.CargarCatalogoWCF(listado);
        }
        
        public System.Collections.Generic.List<BAL.Catalogo> CargarCatalogoDependienteWCF(string listado, string id) {
            return base.Channel.CargarCatalogoDependienteWCF(listado, id);
        }
    }
}
